language: php

php:
  - 7.1

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - travis_retry composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml
  - vendor/bin/phpstan analyze -l 5 src -c phpstan.neon

#after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml