language: php

matrix:
  include:
    - php: 7.2
      dist: bionic
      env: COMPOSER_OPTS=""
    - php: 7.2
      dist: bionic
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: 7.3
      dist: bionic
      env: COMPOSER_OPTS=""
    - php: 7.3
      dist: bionic
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: 7.4
      dist: bionic
      env: COMPOSER_OPTS=""
    - php: 7.4
      dist: bionic
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: nightly
      dist: bionic
      env: COMPOSER_OPTS="--ignore-platform-reqs"
    - php: nightly
      dist: bionic
      env: COMPOSER_OPTS="--ignore-platform-reqs --prefer-lowest"
  allow_failures:
    - php: nightly
      env: COMPOSER_OPTS="--ignore-platform-reqs"
    - php: nightly
      env: COMPOSER_OPTS="--ignore-platform-reqs --prefer-lowest"

cache:
    directories:
        - vendor

sudo: false

install:
    - travis_retry composer install

script:
    - if [[ "${TRAVIS_PHP_VERSION}" == "7.3" ]]; then vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no; fi
    - if [[ "${TRAVIS_PHP_VERSION}" == "7.3" ]]; then vendor/bin/phpstan analyze --level max -c phpstan.neon src; fi
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
